<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\MaterialBase */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tarkibiy-bolinma-form">

    <?php $form = ActiveForm::begin(); ?>



    <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
    $form->field($model, 'building_id')->dropDownList(
        \yii\helpers\ArrayHelper::map(common\models\Building::find()->all(), 'id', 'name'),
        [
            'prompt' => 'Binoni tanlang',
            'disabled' => (isset($relAttributes) || isset($relAttributes['building_id'])),
        ]
    ); ?>

    
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'responce_persion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tarkibiy_bolinma_id')->dropDownList(
        \yii\helpers\ArrayHelper::map(common\models\TarkibiyBolinma::find()->all(), 'id', 'name'),
        [
            'prompt' => 'TarkibiyBolinmani tanlang',
            'disabled' => (isset($relAttributes) || isset($relAttributes['tarkibiy_bolinma_id'])),
        ]
    ); ?>

    <?= $form->field($model, 'status')->dropDownList(\common\helpers\RoomHelper::getStatusList()) ?>



    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
