<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers;
use yii;
use common\models\Building;
use common\models\BuildingSearch;
use yii\web\Controller;

class BuildingController extends BackendController
{

    public function actionIndex()
    {
        $searchModel = new BuildingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $t_b = \common\models\Building::find()->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            't_b' => $t_b,
        ]);
    }


    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    public function actionCreate()
    {
        $model = new Building();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

//    public function actionLists($id)
//    {
//        $posts = \common\models\Room::find()
//            ->where(['category_id' => $id])
//            ->orderBy('id DESC')
//            ->all();
//
//        if (!empty($posts)) {
//            foreach($posts as $post) {
//                echo "<option value='".$post->id."'>".$post->name."</option>";
//            }
//        } else {
//            echo "<option>-</option>";
//        }
//
//    }


    protected function findModel($id)
    {
        if (($model = Building::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}
