<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers;

use Yii;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use common\models\Room;
use common\models\RoomSearch;


use Mpdf\Mpdf;

class RoomController extends BackendController
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'update', 'view', 'create', 'depdf', 'see'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'update', 'view', 'create', 'depdf', 'see'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['see'],
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new RoomSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $t_b = \common\models\Building::find()->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            't_b' => $t_b,
        ]);
    }


    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    public function actionCreate()
    {
        $model = new Room();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }




    public function actionDepdf($id = NULL)
    {
        if ($id == NULL) {
            $id = $_GET["id"];
        }

        $tex2 = \common\models\Room::find()->where(['id' => $id])->one();
        $ttt = \common\models\Building::find()->where(['id' => $tex2->building_id])->one();
         $model = $this->findModel($id);
         $tex = \common\models\TexMainBase::find()
            ->where(['status' => 1])
           ->andWhere(['room_id' => $id])
           ->all();

           $tex12 = \common\models\TexMainBase::findOne(['room_id' => $id]);



        $ped_pdf = new mPDF();

        ob_start();
        echo '<style>
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
              }
              
            </style>';
        echo '<h5 style="text-align: center;">' . $ttt->name . 'si / ' . $tex12->tarkibiyBolinma->name . ' ('.' ' . $model->name . ' )' . '</h5>';
        echo '<table style="width: 100%; ">';
        echo '<tr>';
        echo '<th style="width:5%; text-align: center;">#</th>';
        echo '<th style="width:20%">Nomi</th>';
        echo '<th style="width:20%">Inventer</th>';
        echo '<th style="width:20%">Inventer_b</th>';
        echo '<th style="width:60%">Parametri</th>';


        echo '</tr>';
        $i = 0;
        foreach ($tex as $texOne) {
            echo '<tr> <td style="text-align: center;">' . ++$i . '</td>';
            echo '<td>' . $texOne->tipi->name . '</td>';
            echo '<td style="text-align: center">' . $texOne->inventar_ichki . '</td>';
            echo '<td style="text-align: center">' . $texOne->inventar_b . '</td>';
            echo '<td>' . $texOne->parametr . '</td>
                </tr>';
        }

        echo '</table>';

        echo '<p></p> <p style="text-align: right; margin-right: 50px;"> Mas\'ul:  ' . $tex12->tarkibiyBolinma->rahbar . ' &nbsp;&nbsp; _________ <br> ( imzo )</p> ';
        $c =  'TSUL EUM' . '# \n' . 'http://tech.tsul.uz/backend/room/depdf?id=' . $id ;

        echo '<div style="position: absolute; bottom: 30px; right: 30px;">';
        echo '<barcode code="' . $c . '" size="1.2" type="QR" error="M" class="barcode" />';
        echo '</div>';
        $htmlQR = ob_get_contents();
        ob_end_clean();
        $ped_pdf->WriteHTML($htmlQR);
        $ped_pdf->Output();

        exit;
    }

//    public function actionSee($id)
//    {
//        $this->layout = 'see';
//
//        $tex = TexMainBase::find()
//            ->where(['status' => 1])
//            ->andWhere(['room_id' => $id])
//            ->all();
//        $One = TexMainBase::find()
//            ->where(['status' => 1])
//            ->andWhere(['room_id' => $id])
//            ->one();
//
//        $model = $this->findModel($id);
//
//
////    print_r($One->biriktirilgan);
////    exit();
//        return $this->render('see', [
//            'tex' => $tex,
//            'One' => $One,
//            'model' => $model,
//        ]);
//
//    }


    public function actionLists($id)
    {

        $Rooms = \common\models\Room::find()
            ->where(['building_id' => $id])
            ->orderBy('id')
            ->all();

        if (!empty($Rooms)) {
            foreach ($Rooms as $post) {
                echo "<option value='" . $post->id . "'>" . $post->name . "</option>";
            }
        } else {
            echo "<option> xona yuq </option>";
        }

    }

    protected function findModel($id)
    {
        if (($model = Room::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}
