<?php
namespace backend\controllers;

use common\models\LoginForm;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

use Yii;

/**
 * Site controller.
 * It is responsible for displaying static pages, and logging users in and out.
 */
class SiteController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false; return parent::beforeAction($action);
        if ($action->id == 'login' || $action->id == 'logout')
            $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TOD    O: Change the autogenerated stub
    }

    /**
     * Returns a list of behaviors that this component should behave as.
     *
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['GET'],
                ],
            ],
        ];
    }

    /**
     * Declares external actions for the controller.
     *
     * @return array
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    public function actionIndex()
    {
//        return $this->redirect(['login']);
//        return $this->render('index');

//        return 1;
            return $this->redirect(['tex/index']);
            return $this->render('index');
    }


    public function actionLogin()
    {
        $this->layout = 'authorization';
        if (!Yii::$app->user->isGuest)
        {
             return $this->redirect(['tex/index']);
//             return $this->goHome();
        }

        // get setting value for 'Login With Email'
        $lwe = Yii::$app->params['lwe'];

        // if "login with email" is true we instantiate LoginForm in "lwe" scenario
        $lwe ? $model = new LoginForm(['scenario' => 'lwe']) : $model = new LoginForm() ;

        // everything went fine, log in the user
        if ($model->load(Yii::$app->request->post()) && $model->login())
        {
            return $this->redirect(['tex/index']);
        }
        // errors will be displayed
        else
        {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the user.
     *
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['tex/index']);

//        return $this->goHome();
    }
}
