<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
* @var yii\web\View $this
* @var common\models\MaterialBase $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('models', 'Material Base');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models', 'Material Bases'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud material-base-view">

    <h1>
            <?= Html::encode($model->name) ?>

    </h1>

    </div>

    <hr/>

<p>
    <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    <?= Html::a('index', ['index'], ['class' => 'btn btn-primary']) ?>
    <?= Html::a('Delete', ['delete', 'id' => $model->id], [
        'class' => 'btn btn-danger',
        'data' => [
            'confirm' => 'Are you sure you want to delete this item?',
            'method' => 'post',
        ],
    ]) ?>
</p>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        'name',
        [
            'format' => 'html',
            'inventar',
            'attribute' => 'building_id',
            'value' => ($model->building ?
                Html::a('<i class="glyphicon glyphicon-list"></i>', ['building/index']).' '.
                Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->building->name, ['building/view', 'id' => $model->building->id,]).' '.
                Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'MaterialBase'=>['building_id' => $model->building_id]])
                :
                '<span class="label label-warning">?</span>'),
        ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
        [
            'format' => 'html',
            'attribute' => 'room_id',
            'value' => ($model->room ?
                Html::a('<i class="glyphicon glyphicon-list"></i>', ['room/index']).' '.
                Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->room->name, ['room/view', 'id' => $model->room->id,]).' '.
                Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'MaterialBase'=>['room_id' => $model->room_id]])
                :
                '<span class="label label-warning">?</span>'),
        ],
        'inventar',
        'count',
        'quantity_name',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat


        [
            'attribute' => 'status',
            'value' => function (\common\models\MaterialBase $model) {
                return \common\helpers\MaterialBaseHelper::getStatusLabel($model->status);
            },
            'format'=>'html'
        ],
        'description:ntext',

    ],
    ]); ?>

</div>
