<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models;

use Yii;


/**
 * This is the base-model class for table "building".
 *
 * @property integer $id
 * @property string $name
 * @property string $commandant
 * @property string $description
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property string $aliasModel
 */
class Building extends \yii\db\ActiveRecord
{

    const  STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'building';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['status'], 'integer'],
            [['name','commandant'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'commandant' => 'Komendant',
            'description' => 'Description',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    
    public function getRooms()
    {
        return $this->hasMany(\common\models\Room::className(), ['building_id' => 'id']);
    }




}
