<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models;

use Yii;


/**
 * This is the base-model class for table "material_base".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $inventor
 * @property integer $count
 * @property integer $building_id
 * @property integer $room_id
 * @property integer $type_id
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\Building $building
 * @property \common\models\Room $room
 * @property string $aliasModel
 */
class MaterialBase extends \yii\db\ActiveRecord
{

    const  STATUS_ACTIVE = 1;
    const  STATUS_INACTIVE = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'material_base';
    }

    /**
     * @inheritdoc
     */


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['count', 'type_id', 'status'], 'integer'],
            [['building_id', 'room_id'], 'integer', 'message'=>'xona yuq'],
            [['name', 'inventar'], 'string', 'max' => 255],
            [['building_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Building::className(), 'targetAttribute' => ['building_id' => 'id']],
            [['room_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Room::className(), 'targetAttribute' => ['room_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'quantity_name'=>'Quantity_name',
            'inventar' => 'Inventor',
            'count' => 'Count',
            'building_id' => 'Bino',
            'room_id' => 'Xona',
            'type_id' => 'Type ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuilding()
    {
        return $this->hasOne(\common\models\Building::className(), ['id' => 'building_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoom()
    {
        return $this->hasOne(\common\models\Room::className(), ['id' => 'room_id']);
    }




}
