<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "room".
 *
 * @property integer $id
 * 
 * @property string $name
 * @property string $responce_persion
 * @property integer $building_id
 * @property integer $status
 *
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\Building $building
 * @property string $aliasModel
 */
class Room extends \yii\db\ActiveRecord
{

    const  STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'room';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['building_id', 'status', 'tarkibiy_bolinma_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['responce_persion'], 'string', 'max' => 255],
            [['building_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Building::className(), 'targetAttribute' => ['building_id' => 'id']],
            [['tarkibiy_bolinma_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TarkibiyBolinma::className(), 'targetAttribute' => ['tarkibiy_bolinma_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'building_id' => 'Bino',
            'status' => 'Status',
            'responce_persion' => 'Maʼsul shaxs',
            'tarkibiy_bolinma_id' => 'Tarkibiy Bolinma',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }


    public static function getAlx()
    {
      return  Room::find()
            ->where(['status'=> 1])
            ->andWhere(['building_id' => 'id'])
            ->all();


    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuilding()
    {
        return $this->hasOne(\common\models\Building::className(), ['id' => 'building_id']);
    }

    public function who_recive()
    {
        $who_reciveee = \common\models\TarkibiyBolinma::findOne($this->tarkibiy_bolinma_id);
        return $who_reciveee;
    }

    public function getTarkibiyBolinma()
    {
        return $this->hasOne(\common\models\TarkibiyBolinma::className(), ['id' => 'tarkibiy_bolinma_id']);
    }


}
